### PR TITLE
Rebased main from upstream

### PR DESCRIPTION
**Pull request by ardrigh**
I have pulled and rebased our fork on the upstream `master` branch, which is currently tagged as `3.2.1-rc0`

https://github.com/voxpupuli/puppet-nginx/commit/fffe7a3463e005944799f55f8782e9ba798375a8

Which doesn't appear to have changed any code from the `3.2.0` release looking at `git log`

```shell
* fffe7a3 E [blacksmith] Bump version to 3.2.1-rc0 [Tim Meusel] (tim@bastelfreak.de) 5 weeks ago (voxpupuli/master)
*   0eb9653 E Merge pull request #1457 from bastelfreak/rel320 [Tim Meusel] (tim@bastelfreak.de) 5 weeks ago (tag: v3.2.0)
|\  
| * be73ef6 E Release 3.2.0 [Tim Meusel] (tim@bastelfreak.de) 6 weeks ago
|/  
*   ffa5ad9 E Merge pull request #1456 from bastelfreak/port [Tim Meusel] (tim@bastelfreak.de) 6 weeks ago
```

AFAICT, this still keeps our stream log changes intact. But please double-check our 3 commits are still working.

Note: For the three file conflicts, I had locally removed the content to match the upstream. I might need to add some commits to properly merge those files, so the conflicts go away. 
Or alternatively remove the branch protection to force push the rebase

### CODE REVIEW

**Review by ssodhi — APPROVED** [review]
Mostly upstream changes because of rebase - :+1:

**Comment by yanjunding** [comment]
I think the best way to do this is, rebase our changes to upstream

**Comment by yanjunding** [comment]
https://github.com/voxpupuli/puppet-nginx/pull/1460

**Comment by ardrigh** [comment]
Closing this so we can get a clean apply of the file changes without file conflicts.

**Pull request closed without merging**
